CREATE TABLE IF NOT EXISTS BOOK (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(100) NOT NULL,
  category VARCHAR(20) NOT NULL,
  author VARCHAR(40) NOT NULL,
  publication_date DATE NOT NULL,
  image VARCHAR(255)
);